version: '3.8'
services:
  database:
    image: neo4j:enterprise
    hostname: database
    container_name: database
    env_file:
      - ".env.docker"
    environment:
      - NEO4J_ACCEPT_LICENSE_AGREEMENT=yes
      - NEO4J_AUTH=${NEO4J_USERNAME}/${NEO4J_PASSWORD}
      - NEO4J_PLUGINS='["apoc"]'
      - NEO4J_dbms_default__listen__address=0.0.0.0
    ports:
      - "7474:7474"
      - "7687:7687"
    volumes:
      - database-data:/data
    healthcheck:
      test: [
        "CMD-SHELL",
        "wget --no-verbose --tries=1 --spider localhost:7474 || exit 1"
      ]
      interval: 10s
      timeout: 5s
      retries: 5
  backend:
    hostname: backend
    container_name: backend
    build:
      context: .
    ports:
      - "80:80"
    env_file:
      - ".env.docker"
    depends_on:
      database:
        condition: service_healthy
volumes:
  database-data:
